### ISSUE TITLE
force.zone.values是否应该和awareness.attributes一致

### ISSUE THREAD

**Issue by DUKYASHUO** [mingyitianxia/elastic-certified-engineer#3]
https://github.com/mingyitianxia/elastic-certified-engineer/blob/9b407dc22fd9eb2a93cb23df912f170cc72d0267/review-practice/002_module_01#L130

cluster.routing.allocation.awareness.force.zone.values: earth,mars => cluster.routing.allocation.awareness.force.rack_id.values: earth,mars

**Comment by mingyitianxia** [comment]
ok
已修复，多谢提出bug
